const products = [
  {
    _id: "1",
    name: "Microsoft Surface Pro 9",
    image: "/images/surface pro 9.jpg",
    description:
      "Surface Pro 9 gives you the tablet flexibility you want and the laptop performance and battery life¹ you need to move through your day — all in one ultra-portable device. ",
    brand: "Microsoft",
    category: "Electronics",
    price: 1099.0,
    countInStock: 4,
    rating: 4.5,
    numReviews: 2,
  },
  {
    _id: "2",
    name: "Sony - Playstation 5 Console - Marvel's Spider-Man 2 Bundle - White",
    image: "/images/ps5 spiderman bundle.jpg",
    description: "Playstation 5 Console + Spider-Man 2 Bundle",
    brand: "Sony",
    category: "Consoles and Video Games",
    price: 559.99,
    countInStock: 15,
    rating: 5,
    numReviews: 15,
  },
  {
    _id: "3",
    name: "Microsoft - Xbox Series X Console - Halo Infinite Bundle - Black",
    image: "/images/xbox x halo infinite bundle.jpg",
    description: "Xbox Series X Console + Halo Infinite Bundle",
    brand: "Microsoft",
    category: "Consoles and Video Games",
    price: 579.99,
    countInStock: 10,
    rating: 4.8,
    numReviews: 12,
  },
  {
    _id: "4",
    name: "Nintendo Switch OLED - Mario Kart 8 Deluxe Bundle - Red/Blue",
    image: "/images/oled nintendo switch mario kart 8 bundle.jpg",
    description: "Nintendo Switch OLED + Mario Kart 8 Deluxe Bundle",
    brand: "Nintendo",
    category: "Consoles and Video Games",
    price: 449.99,
    countInStock: 20,
    rating: 4.9,
    numReviews: 18,
  },
  {
    _id: "5",
    name: "Sony - Playstation 5 Console - Demon's Souls Edition - Black",
    image: "/images/ps5 demon souls bundle.jpg",
    description: "Playstation 5 Console + Demon's Souls Edition",
    brand: "Sony",
    category: "Consoles and Video Games",
    price: 599.99,
    countInStock: 8,
    rating: 4.7,
    numReviews: 14,
  },
  {
    _id: "6",
    name: "Nintendo - Switch Lite Console - Animal Crossing Bundle - Pink",
    image: "/images/nintendo switch lite animal crossing bundle pink.jpg",
    description: "Nintendo Switch Lite + Animal Crossing Bundle",
    brand: "Nintendo",
    category: "Consoles and Video Games",
    price: 239.99,
    countInStock: 25,
    rating: 4.5,
    numReviews: 10,
  },
  {
    _id: "8",
    name: "Microsoft - Xbox One S Console - Fortnite Special Edition - Purple",
    image: "/images/xbox one s fortnite purple.jpg",
    description: "Xbox One S Console + Fortnite Special Edition",
    brand: "Microsoft",
    category: "Consoles and Video Games",
    price: 349.99,
    countInStock: 15,
    rating: 4.4,
    numReviews: 9,
  },
  {
    _id: "9",
    name: "Nintendo - Switch Lite Console - Legend of Zelda: Breath of the Wild Bundle - Blue",
    image: "/images/nintendo switch lite botw bundle blue.jpg",
    description:
      "Nintendo Switch Pro + Legend of Zelda: Breath of the Wild Bundle",
    brand: "Nintendo",
    category: "Consoles and Video Games",
    price: 469.99,
    countInStock: 8,
    rating: 4.7,
    numReviews: 13,
  },
  {
    _id: "10",
    name: "Microsoft - Xbox Series S Console - Forza Horizon 5 Bundle - White",
    image: "/images/xbox one s forza bundle.jpg",
    description: "Xbox Series S Console + Forza Horizon 5 Bundle",
    brand: "Microsoft",
    category: "Consoles and Video Games",
    price: 349.99,
    countInStock: 14,
    rating: 4.6,
    numReviews: 7,
  },
];

export default products;
